import type { ReportData } from '../../../src/report/report-data'

/**
 * 仅供 `npm run dev` / `npm run dev:web` 使用的匿名完整报告。
 * 数据刻意覆盖分类、时区、趋势和团队模块，方便在热更新环境中检查整页布局。
 */
export const devReportFixture: ReportData = {
  schemaVersion: '1',
  meta: {
    version: 'dev',
    repos: ['/workspace/code996-demo'],
    since: '2025-07-01',
    until: '2025-12-31',
    rangeMode: 'custom',
    locale: 'zh-CN',
    options: {},
  },
  project: {
    type: 'corporate',
    confidence: 88,
    dimensions: {
      workTimeRegularity: {
        score: 76,
        details: {
          morningUptrend: true,
          afternoonPeak: true,
          eveningDowntrend: true,
          nightLowActivity: false,
        },
      },
      weekendActivity: { ratio: 0.12 },
      moonlightingPattern: { isActive: false, eveningToMorningRatio: 0.28, nightRatio: 0.09 },
      contributorsCount: { count: 6 },
    },
  },
  holidayMode: true,
  timezone: {
    isCrossTimezone: true,
    crossTimezoneRatio: 0.16,
    dominantTimezone: '+0800',
    dominantRatio: 0.84,
    sleepPeriodRatio: 0.04,
    confidence: 86,
    timezoneGroups: [
      { offset: '+0800', count: 538, ratio: 0.84 },
      { offset: '-0700', count: 102, ratio: 0.16 },
    ],
  },
  core: {
    index996: 78,
    rating: 'bad',
    overTimeRatio: 26,
    totalCommits: 640,
  },
  workTime: {
    startHour: 9.5,
    endHour: 21.5,
    isReliable: true,
    sampleCount: 188,
    detectionMethod: 'quantile-window',
    confidence: 84,
    startHourRange: { startHour: 9, endHour: 10 },
    endHourRange: { startHour: 20, endHour: 22 },
    endDetectionMethod: 'backward-threshold',
  },
  hourlyDistribution: Array.from({ length: 24 }, (_, hour) => ({
    hour: String(hour).padStart(2, '0'),
    count: [1, 0, 0, 0, 0, 1, 2, 4, 12, 38, 52, 47, 31, 42, 55, 61, 58, 54, 49, 46, 39, 28, 14, 6][hour],
  })),
  weekdayDistribution: [
    { day: 'monday', count: 108 },
    { day: 'tuesday', count: 116 },
    { day: 'wednesday', count: 112 },
    { day: 'thursday', count: 104 },
    { day: 'friday', count: 96 },
    { day: 'saturday', count: 68 },
    { day: 'sunday', count: 36 },
  ],
  weekdayOvertime: {
    monday: 22,
    tuesday: 28,
    wednesday: 20,
    thursday: 24,
    friday: 18,
    peakDay: 'tuesday',
    peakCount: 28,
  },
  weekendOvertime: {
    saturdayDays: 13,
    sundayDays: 7,
    casualFixDays: 8,
    realOvertimeDays: 12,
  },
  lateNight: {
    evening: 62,
    lateNight: 29,
    midnight: 10,
    dawn: 3,
    midnightDays: 9,
    totalWorkDays: 188,
    midnightRate: 4.8,
    totalWeeks: 26,
    totalMonths: 6,
  },
  trend: {
    timeRange: { since: '2025-07-01', until: '2025-12-31' },
    summary: { totalMonths: 6, avgIndex996: 72.6, avgWorkSpan: 10.8, trend: 'increasing' },
    monthlyData: [
      {
        month: '2025-07',
        index996: 64,
        avgWorkSpan: 9.6,
        workSpanStdDev: 1.8,
        avgStartTime: '09:36',
        avgEndTime: '19:12',
        latestEndTime: '22:48',
        totalCommits: 82,
        contributors: 5,
        workDays: 18,
        dataQuality: 'sufficient',
        confidence: 'high',
      },
      {
        month: '2025-08',
        index996: 68,
        avgWorkSpan: 10.1,
        workSpanStdDev: 2.1,
        avgStartTime: '09:32',
        avgEndTime: '19:38',
        latestEndTime: '23:16',
        totalCommits: 91,
        contributors: 6,
        workDays: 20,
        dataQuality: 'sufficient',
        confidence: 'high',
      },
      {
        month: '2025-09',
        index996: 71,
        avgWorkSpan: 10.5,
        workSpanStdDev: 2.3,
        avgStartTime: '09:28',
        avgEndTime: '19:58',
        latestEndTime: '23:42',
        totalCommits: 104,
        contributors: 6,
        workDays: 21,
        dataQuality: 'sufficient',
        confidence: 'high',
      },
      {
        month: '2025-10',
        index996: 75,
        avgWorkSpan: 11.2,
        workSpanStdDev: 2.6,
        avgStartTime: '09:34',
        avgEndTime: '20:46',
        latestEndTime: '00:18',
        totalCommits: 118,
        contributors: 6,
        workDays: 22,
        dataQuality: 'sufficient',
        confidence: 'high',
      },
      {
        month: '2025-11',
        index996: 77,
        avgWorkSpan: 11.6,
        workSpanStdDev: 2.8,
        avgStartTime: '09:26',
        avgEndTime: '21:02',
        latestEndTime: '00:36',
        totalCommits: 126,
        contributors: 6,
        workDays: 21,
        dataQuality: 'sufficient',
        confidence: 'high',
      },
      {
        month: '2025-12',
        index996: 81,
        avgWorkSpan: 12,
        workSpanStdDev: 3.1,
        avgStartTime: '09:30',
        avgEndTime: '21:30',
        latestEndTime: '01:08',
        totalCommits: 119,
        contributors: 6,
        workDays: 19,
        dataQuality: 'sufficient',
        confidence: 'high',
      },
    ],
  },
  team: {
    totalAnalyzed: 3,
    totalContributors: 6,
    filterThreshold: 20,
    baselineEndHour: 21.5,
    distribution: { normal: 1, moderate: 1, heavy: 1 },
    statistics: {
      median996: 76,
      mean996: 74,
      range: [58, 88],
      percentiles: { p25: 65, p50: 76, p75: 82, p90: 88 },
    },
    healthAssessment: { overallIndex: 76, teamMedianIndex: 76 },
    contributors: [
      {
        author: 'Developer A',
        email: 'developer-a@example.invalid',
        totalCommits: 252,
        commitPercentage: 39.38,
        avgStartTimeMedian: 9.25,
        avgEndTimeMedian: 22,
        validDays: 46,
        index996: 88,
        overtimeStats: { workdayOvertime: 54, weekendOvertime: 18, totalOvertime: 72 },
        intensityLevel: 'heavy',
      },
      {
        author: 'Developer B',
        email: 'developer-b@example.invalid',
        totalCommits: 214,
        commitPercentage: 33.44,
        avgStartTimeMedian: 9.5,
        avgEndTimeMedian: 20.5,
        validDays: 42,
        index996: 76,
        overtimeStats: { workdayOvertime: 38, weekendOvertime: 12, totalOvertime: 50 },
        intensityLevel: 'moderate',
      },
      {
        author: 'Developer C',
        email: 'developer-c@example.invalid',
        totalCommits: 174,
        commitPercentage: 27.18,
        avgStartTimeMedian: 10,
        avgEndTimeMedian: 19,
        validDays: 38,
        index996: 58,
        overtimeStats: { workdayOvertime: 21, weekendOvertime: 7, totalOvertime: 28 },
        intensityLevel: 'normal',
      },
    ],
  },
  multiRepo: null,
}
